--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/PocketFuzy
build-by-default: true
branches:
- apimap
projects:
  tests.plugins.TesterPlugin:
    path: tests/plugins/TesterPlugin/
...
